development:
  adapter: postgresql
  host: localhost
  encoding: utf-8
  database: mapbuilder_development
  pool: 5
  username: postgres
  password: secret

test:
  adapter: postgresql
  host: localhost
  encoding: utf-8
  database: mapbuilder_test
  pool: 5
  username: postgres
  password: secret


production:
  adapter: postgresql
  host: localhost
  encoding: utf-8
  database: mapbuilder_production
  pool: 5
  username: postgres
  password: secret

