development:
  adapter: postgresql
  encoding: unicode
  database: mapbuilder_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: mapbuilder_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: mapbuilder_production
  pool: 5
  host: localhost
