development: &defaults
  adapter: postgresql
  encoding: unicode
  database: mapbuilder
  pool: 5

test:
  <<: *defaults
  database: mapbuilder_test

staging:
  <<: *defaults
  database: mapbuilder_staging

production:
  <<: *defaults

