development: &defaults
  adapter: postgresql
  encoding: unicode
  database: mapbuilder
  username: rails
  password: dev
  pool: 5
  host: localhost

test:
  <<: *defaults
  database: mapbuilder_test

staging:
  <<: *defaults
  databse: mapbuilder_staging

production:
  <<: *defaults
